---
title: Test
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
localization:
  read-more: Read more
  see-all-posts: See all posts
markdown: kramdown
