---
title: Test
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: post
localization:
  read-more: Read more
  see-all-posts: See all posts
markdown: kramdown
archive: archive
favicon: images/logo/logo-64x64.png
